### PR TITLE
Remove additional volatile cell data during cleaning

### PR DESCRIPTION
**Pull request by mwaskom**
This should produce cleaner notebooks diffs

### CODE REVIEW

**Review by spirosChv — COMMENTED** [review]
tested against

1. [--execute](https://github.com/NeuromatchAcademy/course-content-dl/pull/84/commits/40d3ee14150b7462196c1dbf7afcada899f9f0a6)
2. [--check-execution](https://github.com/NeuromatchAcademy/course-content-dl/pull/84/commits/fed4a4d47b78c5f00ebdb1ba2f90280c5d47e381)

**Comment by mwaskom** [comment]
Thanks, looks like I was cleaning fields from not quite the right place so it wasn't working properly. Can you try again? Thanks!

**Comment by spirosChv** [comment]
> Thanks, looks like I was cleaning fields from not quite the right place so it wasn't working properly. Can you try again? Thanks!

Done [here](https://github.com/NeuromatchAcademy/course-content-dl/pull/84/commits/f42ce216b1a2fe5e8a48e619529650be0a3938ab)

**Comment by spirosChv** [comment]
@mwaskom should I merge this PR?

**Comment by mwaskom** [comment]
Yes I think this is good to go. I guess just keep an eye on the first couple of merges to make sure there aren't any weird issues with widgets or outputs. (Unfortunately I don't think all the metadata that colab injects is documented anywhere, but it can open .ipynbs from github that have never been through colab just fine, so I don't think any of it is critical).

**Pull request merged**
